## YAML Template.
---
plugins: [sample, eg_plugin, about, databrowser]
navbar:
    menu:
        available_items:
            search: 
                path: search/?q=*
                label: Search Data
                icon: search
            narrative: 
                uri: funtional_site#narrativemanager/start
                label: Narrative
                icon: file
            narrativeTutorial: 
                uri: https://kbase.us/narrative-guide
                label: Narrative Tutorial
                icon: info-circle
            contact: 
                path: contact
                label: Contact Us
                icon: envelope-o
            about_kbase: 
                uri: https://kbase.us/about
                label: About KBase
                icon: info-circle
            contact_us:
                uri: https://kbase.us/contact-us
                label: Contact Us
                icon: envelope-o
            dashboard:
                path: dashboard
                label: Dashboard
                icon: dashboard
            typebrowser:
                path: typebrowser
                label: Type Browser
                icon: beer
            test: 
                path: test
                label: Testing Panel
                icon: flask
            linechart:
                path: linechart
                label: Line Chart
                icon: line-chart
            barchart:
                path: barchart
                label: Bar Chart
                icon: bar-chart
            heatmap:
                path: heatmap
                label: Heat Map
                icon: barcode
            scatterplot:
                path: scatterplot
                label: Scatter Plot
                icon: ellipsis-h
        menus:
            authenticated: [search, narrative, dashboard, typebrowser, test, divider, linechart, barchart, heatmap, scatterplot, divider, about, contact, divider]                
            unauthenticated: [about, contact, divider, about_kbase, contact_us]
        
